#!/bin/sh -x

# shellcheck source=dotfiles/profile
. .profile

# No bell
xset b 0 0 0

command -v openbsd-wallpaper \
	> /dev/null 2> /dev/null \
	&& openbsd-wallpaper &

command -v cwm \
	> /dev/null 2> /dev/null \
	&& exec cwm

