#!/bin/sh -x

# shellcheck source=dotfiles/profile
. .profile

# No bell
xset b 0 0 0

openbsd-wallpaper &

# termbar
#exec xterm -fs 12 -bg "black" -fg "grey" -name termbar -class termbar -T termbar -e ~/code/termbar/termbar &
exec xterm -fs 12 -bg "black" -fg "grey" -name termbar -class termbar -T termbar -e ~/scripts/termbar &

exec cwm

