#!/bin/sh

# shellcheck disable=SC2139
alias vi="${EDITOR}"

# shellcheck disable=SC2139
alias view="${EDITOR}ew"

# shellcheck disable=SC2139
alias ex="${EDITOR%vi}ex"

if test "${ME_CONTEXT}" = "work"
then
	#
	# Aliases
	#

	# Tailscale might be installed either by Homebrew or by the AppStore
	test -f /Applications/Tailscale.app/Contents/MacOS/Tailscale && alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"

	# Get all resource IDs in Terraform state
	# From another developer and in Powershell. Will convert later.
	alias get_terraform_resource_ids="terraform state list | %{ $a=$_; terraform state show $_ 2>$null | Select-String -Pattern "\s+id\s+" | % { $_.ToString().Replace('id', $a) } }"

	# Playback rate... apparently this was useful somewhere to speed-up a video...
	alias playback_rate_example="document.querySelector('video').playbackRate = 2.0;"

	#
	# Subroutines
	#

	get_haproxy_domains()
	{
		# Assumes no whitespace in filenames #

		if test -z "${*}"
		then
			printf 'Pass at least one file to search.\n' >&2
			return 1
		fi

		# shellcheck disable=SC2048
		for i in ${*}
		do
			grep -orE '([a-z]+\.)*[a-z]+\.(com|dev|io|net|org)' "${i}" |
				grep -vE '^[[:space:]]*#' |
				awk -F':' '{ print $2; }'
		done | sort | uniq
	}

	test_mail3_logos_com()
	{
		__test_mail3_logos_com__email="$(git config user.email)"
		__test_mail3_logos_com__lines="EHLO abc.com|
		MAIL FROM: $(git config user.email)|
		MAIL FROM: $(git config user.email)|
		RCPT TO: $(git config user.email)|
		DATA|
		From: $(git config user.email)\nMIME-Version: 1.0 (mime-construct 1.9)\n\n|
		Hostname: $(uname -n)|
		.|
		quit"

		IFS='|'
		for i in ${__test_mail3_logos_com__lines}
		do
			printf '%s' "${i}"
			sleep 1
		done | nc -v mail3.logos.com 25
		unset IFS
	}
fi
