#!/bin/sh

# shellcheck disable=SC2139
alias vi="${EDITOR}"

# shellcheck disable=SC2139
alias view="${EDITOR}ew"

# shellcheck disable=SC2139
alias ex="${EDITOR%vi}ex"

if test "${ME_CONTEXT}" = "work"
then
	# Tailscale might be installed either by Homebrew or by the AppStore
	test -f /Applications/Tailscale.app/Contents/MacOS/Tailscale && alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
fi

