#!/bin/sh

LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
ENV="${HOME}/.kshrc"
SHELL="/usr/bin/tmux"
export LANG LC_CTYPE ENV SHELL

# No bell
xset b 0 0 0

# "Include" config from .xresources
xrdb -merge "${HOME}"/.xresources

# Per config in .xresources, xidle
# will eventually lock the screen
xidle &

# Set Caps_Lock to be another Escape
setxkbmap -option caps:ctrl_modifier

# Wallpaper randomization process
command -v openbsd-wallpaper \
	> /dev/null 2> /dev/null \
	&& openbsd-wallpaper &

# Start ssh-agent as needed
test -z "${SSH_AGENT_PID}" && eval `ssh-agent -s`

# Launch the built-in CWM window manager
command -v cwm \
	> /dev/null 2> /dev/null \
	&& exec cwm

