#!/bin/sh

readonly LANG="en_US.UTF-8"
readonly LC_CTYPE="en_US.UTF-8"
ENV="${HOME}/.kshrc"; readonly ENV
readonly SHELL="/usr/bin/tmux"
ME_NCPU="$(sysctl hw.ncpu | awk -F '=' '{print $2;}')"
readonly ME_NCPU
export LANG LC_CTYPE ENV SHELL ME_NCPU

ME_GUI="false"
test "${ME_NCPU}" -ge "4" && ME_GUI="true"
readonly ME_GUI
export ME_GUI

ME_HIGH_PERFORMANCE="false"
test "${ME_NCPU}" -ge "8" && ME_HIGH_PERFORMANCE="true"
readonly ME_HIGH_PERFORMANCE
export ME_HIGH_PERFORMANCE

# No bell
xset b 0 0 0

# "Include" config from .xresources
xrdb -merge "${HOME}"/.xresources

# Per config in .xresources, xidle
# will eventually lock the screen
xidle &

# Set Caps_Lock to be another Escape
setxkbmap -option caps:ctrl_modifier

# Wallpaper randomization process
command -v openbsd-wallpaper \
	> /dev/null 2> /dev/null \
	&& openbsd-wallpaper &

# Start ssh-agent as needed
test -z "${SSH_AGENT_PID}" && eval "$(ssh-agent -s)"

# Conditionally launch the built-in CWM window manager
if test "true" = "${ME_GUI}"
then
	command -v cwm \
		>/dev/null \
		2>/dev/null \
		&& exec cwm
else
	command -v xterm \
		>/dev/null \
		2>/dev/null \
		&& exec xterm -maximize
fi
